server:
    port: 8080

logging:
    file: spring.log

debug: true


spring:
    datasource:
        url: jdbc:mysql://localhost:3306/autochess?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: autochess
        password: autochess123
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                format_sql: true
        show-sql: true
    devtools:
        restart:
            enabled: false   #热部署生效
            additional-paths: src/,resources/    #设置刷新目录
    freemarker:
        cache: false
    thymeleaf:
        cache: true

mybatis:
    type-aliases-package: com.accenture.huaweigroup.module.entity
    mapper-locations: classpath:mapper/*.xml



#
#    spring.datasource.url=
#spring.datasource.username=autochess
#spring.datasource.password=autochess123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#spring.jpa.properties.hibernate.hbm2ddl.auto=update
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#
#mybatis.type-aliases-package=com.accenture.huaweigroup.module.mapper